name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - erlang: "24.1.7"
            elixir: "1.13.0"
            lint: true
          - erlang: "24.1.7"
            elixir: "1.12.3"
          - erlang: "23.3.4"
            elixir: "1.11.4"
          - erlang: "23.3.4"
            elixir: "1.10.4"
          - erlang: "22.3.4"
            elixir: "1.9.4"
          - erlang: "21.3.8"
            elixir: "1.8.2"
          - erlang: "20.3.8"
            elixir: "1.7.4"
          - erlang: "19.3.6"
            elixir: "1.6.6"
    steps:
      - uses: actions/checkout@v1

      - name: Install OTP and Elixir
        uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.erlang}}
          elixir-version: ${{matrix.elixir}}

      - name: Install dependencies
        run: mix deps.get

      - name: Check for unused dependencies
        run: mix deps.unlock --check-unused
        if: ${{matrix.lint}}

      - name: Compile with --warnings-as-errors
        run: mix compile --warnings-as-errors
        if: ${{matrix.lint}}

      - name: Check mix format
        run: mix format --check-formatted
        if: ${{matrix.lint}}

      - name: Run tests
        run: mix test
